# Generated by Django 4.1.7 on 2023-02-19 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 11, 15, 25, 512034, tzinfo=datetime.timezone.utc)),
        ),
    ]
